#!/bin/bash

if [[ -z $1 ]]; then
  echo -e "\e[31mError: Please provide the name of the C++ file to compile.\e[0m"
  exit 1
fi

cpp_file=$1
output_file="${cpp_file%.*}.out"

g++ "$cpp_file" -std=gnu++17 -D DEBUG -o "$output_file" 2>&1

if [[ $? -eq 0 ]]; then
  echo -e "\e[32mCompilation successful. Running the program:\e[0m"
  cat input.txt | ./"$output_file"
else
  echo -e "\e[31mCompilation failed.\e[0m"
fi
